// <auto-generated />
using System;
using Instagroceries.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Instagroceries.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200124104820_Initial create")]
    partial class Initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Instagroceries.Models.Test1", b =>
                {
                    b.Property<Guid>("Test1ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<Guid>("Test2ID");

                    b.HasKey("Test1ID");

                    b.HasIndex("Test2ID");

                    b.ToTable("Test1s");
                });

            modelBuilder.Entity("Instagroceries.Models.Test2", b =>
                {
                    b.Property<Guid>("Test2ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LastName");

                    b.HasKey("Test2ID");

                    b.ToTable("Test2s");
                });

            modelBuilder.Entity("Instagroceries.Models.Test1", b =>
                {
                    b.HasOne("Instagroceries.Models.Test2", "Test2")
                        .WithMany("Test1s")
                        .HasForeignKey("Test2ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
